# Generated by Django 5.2.4 on 2025-07-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_remove_order_ordered_at_order_address_order_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='SweetOrder',
        ),
    ]
