# Generated by Django 5.2.4 on 2025-07-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_rename_order_sweetorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
